steps:
- id: go_build
  name: golang
  args: ['go', 'build', '-ldflags=-s -w', '.']
  env: ["CGO_ENABLED=0"]
- id: go_test
  name: golang
  args: ['go', 'test']
- id: go_security
  name: securego/gosec
  args: [./...]
  env: [GOPATH=.]
- id: docker_image_build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/devops-lab', '.']
- id: docker_image_push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/devops-lab']
- id: cloud_run_deploy
  name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'devops-lab',
    '--image', 'gcr.io/$PROJECT_ID/devops-lab',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--set-env-vars=LASTCOMMITSHA=$COMMIT_SHA, VERSION=$TAG_NAME' ## Uses builtin substitutions for version and commit SHA
    ]
# - id: gke_deploy ## Requires modifying IAM permissions https://cloud.google.com/cloud-build/docs/deploying-builds/deploy-gke#required_iam_permissions
#   name: 'gcr.io/cloud-builders/gke-deploy:stable'
#   args: [
#     'run',
#     '--filename=kubernetes',
#     '--location=us-central1-a',
#     '--cluster=standard-cluster-1'
#   ]
# test