
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab
  namespace: lab
  labels:
    app: devops-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-lab
  template:
    metadata:
      labels:
        app: devops-lab
    spec:
      containers:
      - name: devops-lab
        image: gcr.io/ira-nz/devops-lab:latest
        ports:
        - containerPort: 8080
        env:
          - name: "VERSION"
            valueFrom:
              configMapKeyRef:
                key: "VERSION"
                name: "devops-lab-config"
          - name: "LASTCOMMITSHA"
            valueFrom:
              configMapKeyRef:
                key: "LASTCOMMITSHA"
                name: "devops-lab-config"